-- Phase 6 enablers: the real-time event stream (PLAN §5.10) + record
-- hard-delete archival (ADR-0006 / ADR-0015).
--
-- (1) sys_event_log — the canonical, sequence-numbered domain-event stream.
--     Written in the SAME transaction as the data write (§5.9.3 step 7),
--     alongside the heavier compliance audit (sys_audit_log) and the outbox.
--     Real-time/replay read from here; the SSE relay fans it out (§5.10).
--     A global BIGSERIAL `seq` is monotonic and unique and serves as the SSE
--     Last-Event-ID cursor (replay is additionally filtered by tenant_id).
--     Time-partitioning + retention arrive with §5.15 (same bucket as
--     sys_audit_log); a plain, well-indexed table for now.
--
-- (2) biz_archive — per-entity archive tables generated at publish time by the
--     DDL engine (mda-data::ddl), plus a generic BEFORE DELETE trigger that
--     copies every deleted row (incl. cascade-deleted children) so a hard
--     delete is reversible (ADR-0006). Restore is batch-scoped in the full
--     ADR-0015 design; single-record restore ships now.

-- ===== helpers schema (platform trigger functions) =====
CREATE SCHEMA IF NOT EXISTS mda;

-- ===== sys_event_log =====
CREATE TABLE sys_event_log (
    seq         BIGSERIAL   PRIMARY KEY,
    tenant_id   UUID        NOT NULL,
    ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
    type        TEXT        NOT NULL,    -- record.created | record.updated | record.deleted | workflow.transitioned | metadata.published | notification.*
    entity      TEXT,
    record_id   UUID,
    actor_id    UUID,
    payload     JSONB       NOT NULL DEFAULT '{}'::jsonb  -- changed_fields[], from_version, to_version, transition...
);
CREATE INDEX IF NOT EXISTS sys_event_log_tenant_seq_idx
    ON sys_event_log (tenant_id, seq);
CREATE INDEX IF NOT EXISTS sys_event_log_tenant_entity_record_idx
    ON sys_event_log (tenant_id, entity, record_id, seq);

-- Fan-out: every new event row notifies all app instances (§5.10.4). Each
-- instance's LISTEN worker then reads the row and pushes to its local SSE
-- clients. Postgres NOTIFY spans replicas; Redis is only the scale-path later.
CREATE OR REPLACE FUNCTION mda.notify_event() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('mda_event', NEW.seq::text);
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS sys_event_log_notify ON sys_event_log;
CREATE TRIGGER sys_event_log_notify
    AFTER INSERT ON sys_event_log
    FOR EACH ROW EXECUTE FUNCTION mda.notify_event();

-- ===== biz_archive scaffolding =====
--
-- Each entity publishes to biz.<table> AND gets a matching biz_archive.<table>
-- (generated by mda-data::ddl at publish). A single generic trigger function
-- archives any biz row into its biz_archive twin on DELETE, copying only the
-- non-generated columns (GENERATED ALWAYS columns can't be inserted into, and
-- the archive copy is a plain stored column anyway). Column additions on biz
-- are mirrored to biz_archive by the DDL engine so the positional-by-name
-- insert stays valid.
CREATE SCHEMA IF NOT EXISTS biz_archive;

CREATE OR REPLACE FUNCTION mda.archive_row() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    cols text;
    refs text;
BEGIN
    SELECT string_agg(quote_ident(a.attname), ', ')
      INTO cols
      FROM pg_attribute a
     WHERE a.attrelid = TG_RELID
       AND a.attnum > 0
       AND NOT a.attisdropped
       AND a.attgenerated = '';           -- skip GENERATED ALWAYS columns

    SELECT string_agg('$1.' || quote_ident(a.attname), ', ')
      INTO refs
      FROM pg_attribute a
     WHERE a.attrelid = TG_RELID
       AND a.attnum > 0
       AND NOT a.attisdropped
       AND a.attgenerated = '';

    EXECUTE format(
        'INSERT INTO biz_archive.%I (%s, archived_at) VALUES (%s, now())',
        TG_TABLE_NAME, cols, refs
    ) USING OLD;
    RETURN OLD;
END;
$$;
