[package]
name = "mda-reports"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mda-core = { workspace = true }
mda-meta = { workspace = true }
mda-data = { workspace = true }
mda-security = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
