[package]
name = "mda-meta"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mda-core = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
moka = { version = "0.12", features = ["future"] }
