[package]
name = "mda-data"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mda-core = { workspace = true }
mda-meta = { workspace = true }
mda-expression = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
